In [1]:
import pandas as pd


In [3]:
df=pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [61]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
x=df.filter(['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'])
y=df['Species']
#from sklearn.preprocessing import OneHotEncoder
#le=OneHotEncoder()
#yencoded=le.fit_transform(y)
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
yencoded=le.fit_transform(y)
print(yencoded)
X_train,X_test,y_train,y_test=train_test_split(x,yencoded,test_size=0.2,random_state=42)
X_train.shape
y_train = tf.keras.utils.to_categorical(y_train, 3)
y_test = tf.keras.utils.to_categorical(y_test, 3)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [62]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [63]:
model=Sequential()
model.add(Dense(16, input_dim=4,activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [64]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [65]:
history=model.fit(X_train,y_train,epochs=100,batch_size=20)

Epoch 1/100
6/6 [==============================] - 1s 3ms/step - loss: 1.0959 - accuracy: 0.3981
Epoch 2/100
6/6 [==============================] - 0s 4ms/step - loss: 1.0863 - accuracy: 0.4408
Epoch 3/100
6/6 [==============================] - 0s 3ms/step - loss: 1.0758 - accuracy: 0.6379
Epoch 4/100
6/6 [==============================] - 0s 3ms/step - loss: 1.0622 - accuracy: 0.6514
Epoch 5/100
6/6 [==============================] - 0s 3ms/step - loss: 1.0472 - accuracy: 0.6342
Epoch 6/100
6/6 [==============================] - 0s 3ms/step - loss: 1.0216 - accuracy: 0.6913
Epoch 7/100
6/6 [==============================] - 0s 3ms/step - loss: 0.9905 - accuracy: 0.6804
Epoch 8/100
6/6 [==============================] - 0s 2ms/step - loss: 0.9619 - accuracy: 0.6651
Epoch 9/100
6/6 [==============================] - 0s 2ms/step - loss: 0.9175 - accuracy: 0.6520
Epoch 10/100
6/6 [==============================] - 0s 3ms/step - loss: 0.8619 - accuracy: 0.6620
Epoch 11/100
6/6 [===========

In [70]:
import numpy as np
y_pred=model.predict(X_test)
pred=list()
for i in range(len(y_pred)):
  pred.append(np.argmax(y_pred[i]))
test=list()
for i in range(len(y_test)):
  test.append(np.argmax(y_test[i]))
print(y_pred)

[[2.0932084e-05 9.9303740e-01 6.9416347e-03]
 [9.9970454e-01 2.9547894e-04 3.5143561e-09]
 [8.1407449e-14 9.1964612e-04 9.9908030e-01]
 [6.2523695e-06 9.7372437e-01 2.6269415e-02]
 [1.5644475e-05 9.9601364e-01 3.9706719e-03]
 [9.9954396e-01 4.5596305e-04 9.9884998e-09]
 [9.1835874e-04 9.9843651e-01 6.4512948e-04]
 [7.1317607e-10 7.5086094e-02 9.2491388e-01]
 [2.3285152e-06 8.1379312e-01 1.8620455e-01]
 [5.5376120e-04 9.9863523e-01 8.1092049e-04]
 [9.3704635e-09 2.4090330e-01 7.5909674e-01]
 [9.9899918e-01 1.0006712e-03 6.5770024e-08]
 [9.9952292e-01 4.7707901e-04 1.1186994e-08]
 [9.9914384e-01 8.5619191e-04 4.5189665e-08]
 [9.9950349e-01 4.9644936e-04 1.1014750e-08]
 [4.5543461e-06 9.8834991e-01 1.1645490e-02]
 [1.1268655e-12 1.8750188e-03 9.9812502e-01]
 [5.1197514e-04 9.9824739e-01 1.2407126e-03]
 [1.0851424e-05 9.7522664e-01 2.4762491e-02]
 [2.4097701e-12 2.2464565e-03 9.9775356e-01]
 [9.9910766e-01 8.9227536e-04 4.6268539e-08]
 [4.3260737e-08 3.3773297e-01 6.6226697e-01]
 [9.993293

In [72]:
print(pred)
from sklearn.metrics import accuracy_score
a= accuracy_score(pred,test)
print(a*100)

[1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0]
100.0
