In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("iris.csv")

In [6]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [9]:
df.replace('setosa',1,inplace=True)

In [10]:
df.replace('versicolor',2,inplace=True)

In [11]:
df.replace('virginica',3,inplace=True)

In [13]:
df['species'].unique()

array([1, 2, 3], dtype=int64)

In [14]:
X=df.drop('species',axis=1)

In [42]:
y=df[['species']]

In [71]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y ,random_state=424)

In [72]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [73]:
cfll_sum=SVC()

In [74]:
cfll_sum.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [75]:
output= cfll_sum.predict(X_test)

In [76]:
output

array([2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 3, 3, 3, 2, 3, 3, 2, 1, 2, 3, 3,
       1, 1, 3, 3, 3, 3, 1, 3, 2, 3, 1, 2, 3, 1, 1, 1, 1, 1, 2, 3, 2, 1,
       3], dtype=int64)

In [77]:
y_test

species
55         2
86         2
35         1
72         2
11         1
67         2
53         2
92         2
23         1
57         2
30         1
148        3
104        3
143        3
98         2
112        3
101        3
61         2
36         1
62         2
109        3
100        3
45         1
18         1
117        3
132        3
139        3
83         2
42         1
141        3
87         2
120        3
4          1
95         2
125        3
6          1
26         1
16         1
29         1
20         1
75         2
126        3
51         2
32         1
103        3

In [78]:
accuracy_score(y_test, output)*100

97.77777777777777

In [79]:
from sklearn.model_selection import KFold
SVC1=SVC()
param_grid= {'C': [0.2,0.5,1,5,10,20],'gamma' : ['scale', 'auto'], 'kernel' : ['linear','rbf']}

randomized_search=RandomizedSearchCV(cfll_sum,param_grid)

In [80]:
randomized_search.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_

RandomizedSearchCV(cv='warn', error_score='raise-deprecating',
          estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
          fit_params=None, iid='warn', n_iter=10, n_jobs=None,
          param_distributions={'C': [0.2, 0.5, 1, 5, 10, 20], 'gamma': ['scale', 'auto'], 'kernel': ['linear', 'rbf']},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0)

In [81]:
randomized_search.best_params_

{'kernel': 'rbf', 'gamma': 'scale', 'C': 5}

In [82]:
clf_tuned=SVC(C=1,kernel='rbf',gamma='scale')

In [83]:
clf_tuned.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [84]:
outputt=clf_tuned.predict(X_test)

In [85]:
outputt

array([2, 2, 1, 3, 1, 2, 2, 2, 1, 2, 1, 3, 3, 3, 2, 3, 3, 2, 1, 2, 3, 3,
       1, 1, 3, 3, 3, 3, 1, 3, 2, 3, 1, 2, 3, 1, 1, 1, 1, 1, 2, 3, 2, 1,
       3], dtype=int64)

In [86]:
accuracy_score(y_test, outputt)*100

95.55555555555556

In [87]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,outputt)

array([[15,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 15]], dtype=int64)

In [88]:
from sklearn.metrics import classification_report

In [89]:
y_true,y_predd=y_test,clf_tuned.predict(X_test)
print('Report')
print(classification_report(y_true,y_predd))

Report
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        15
           2       1.00      0.87      0.93        15
           3       0.88      1.00      0.94        15

   micro avg       0.96      0.96      0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

